#WEIGHT
library(shiny)
require(shiny);require(plotly);require(tidyr);require(lazyeval)
fluidPage(shinyUI(navbarPage(p("AAF", style="font-family:Impact;color:#ad1d28;font-size:40px;"),
                             tabPanel("Daily Energy Expenditure",
                                      column(strong("Enter Your Data:"),width=4,
                                             div(class = "option-group",
                                                 wellPanel(radioButtons("gender", "Gender", choices = c("Female", "Male"),
                                                                        inline = TRUE),
                                                           radioButtons("activity", "Activity Type",
                                                                        c("Sedentary", "Moderate","Strenous"), inline = FALSE),
                                                           numericInput("age","Age?",
                                                                        value=0, min=1, max=100, step=1),
                                                           numericInput("weight","Weight(kg)?",
                                                                        value=0, min=1, max=500, step=10),
                                                           numericInput("height","Height(cm)?",
                                                                        value=0, min=1, max=300, step=10),
                                                           actionButton("goButton", "Go!")),
                                                 wellPanel(tags$p(strong("Total Energy Expenditure (kcal):")),
                                                           verbatimTextOutput("TEE"))
                                             )),
                                      column(width=7,
                                             div(class="te",
                                                 pre(includeText("include1.txt")),
                                                 strong("To make sure the calculator work as intended, please only enter positive and reasonable values! All code for this shiny app can be found at https://github.com/wenwen829/AAF")
                                                 ))
                           ),
                             tabPanel("Body Metrix",
                                      column(strong("Enter Your Data:"),width=6,
                                             div(class = "option-group1",
                                                 wellPanel(radioButtons("gender1", "Gender",
                                                                        choices = c("Female", "Male"), inline = TRUE),
                                                           numericInput("age1","Age?",
                                                                        value=0, min=1, max=100, step=1),
                                                           numericInput("weight1","Weight(kg)?",
                                                                        value=0, min=1, max=500, step=10),
                                                           numericInput("height1","Height(cm)?",
                                                                        value=0, min=1, max=300, step=10),
                                                           numericInput("waist1","Waist(cm)?",
                                                                        value=0, min=1, max=200, step=1),
                                                           numericInput("hip1","Hip(cm)?",
                                                                        value=0, min=1, max=200, step=1),
                                                           actionButton("report","Generate Report")),
                                                          strong("To make sure the calculator work as intended, please only enter positive and reasonable values!"),
                                                 pre(includeText("include2.txt"))
                                             )),
                                      column(strong("Your Results:"),width=5,
                                             div(class = "option-group2",
                                                 wellPanel(tags$p(strong("IBW (kg)")),
                                                           verbatimTextOutput("IBW"),
                                                           tags$p(strong("%IBW")),
                                                           verbatimTextOutput("pIBW"),
                                                           tags$p(strong("BSA(m2)")),
                                                           verbatimTextOutput("bsa"),
                                                           tags$p(strong("BMI")),
                                                           verbatimTextOutput("BMI"),
                                                           tags$p(strong("BMI class")),
                                                           verbatimTextOutput("BMIc"),
                                                           tags$p(strong("WHRatio")),
                                                           verbatimTextOutput("ratio"),
                                                           htmlOutput("check"),
                                                           tags$p(strong("Total Heart (bpm)")),
                                                           verbatimTextOutput("hrt"),
                                                           tags$p(strong("HRm(bpm)")),
                                                           verbatimTextOutput("hrm")
                                                           )
                                                 ))
                             ),
                             tabPanel("Weight Planner",
                                      column(strong("Enter Your Data:"),width=4,
                                             div(class = "option-group3",
                                                 wellPanel(numericInput("starting","Starting Weight (kg):",
                                                                         value=0, min=1, max=20000, step=100),
                                                          hr(),
                                                          strong("PLAN1"),
                                                          numericInput("totale","Daily Energy Expenditure",
                                                                        value=0, min=1, max=20000, step=100),
                                                          numericInput("eintake","Calories Intake(kcal/d)",
                                                                        value=0, min=1, max=500, step=10),
                                                          hr(),
                                                          strong("PLAN2"),
                                                          numericInput("totale1","Daily Energy Expenditure",
                                                                        value=0, min=1, max=20000, step=100),
                                                          numericInput("eintake1","Calories Intake(kcal/d)",
                                                                        value=0, min=1, max=500, step=10),
                                                          actionButton("simulate","Simulate"))
                                             ),strong("Fill two diet plans in the panel above using only positive values, then press the simulate button to see how their outcomes differ over 60 days period. Daily Energy Expenditure can be calculated using the first panel of this app.")),
                                      mainPanel(strong("Expected Weight Change Over 60 days"), br(),
                                                "Click the play button below to see line chart",
                                                plotlyOutput("plot1")
                                      )
))))



